
spring:
  datasource:
    url: jdbc:mysql://10.139.60.170:3306/mos-news?useUnicode=true&amp&characterEncoding=utf-8&amp&serverTimezone=GMT%2B8&amp&useSSL=false
    password: 1234567a
    username: mosuser
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 3000
      idle-timeout: 30000
      max-lifetime: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  batch:
    jdbc:
      initialize-schema: NEVER
    job:
      enabled: false
server:
  port: 8080

#logging:
#  level:
#    org.springframework: debug

