
spring:
  datasource:
    url: jdbc:mysql://10.139.60.170:3306/mos-news?useUnicode=true&amp&characterEncoding=utf-8&amp&serverTimezone=GMT%2B8&amp&useSSL=false
    password: 1234567a
    username: mosuser
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
server:
  port: 8080


